import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
await p.goto("http://127.0.0.1:8099/page.html");
await p.waitForTimeout(2500);
const rail = await p.evaluate(() => !!document.getElementById("lahe-surface-root"));
console.log("overlay mounted:", rail, "console errors:", errs.slice(0,3));
await b.close();
