// `lahe reply`: the one command that writes a reply line, so no shell has to
// encode JSON.
//
// The incident this exists for: an agent appended a reply with a shell echo and
// a multi-paragraph answer. The raw newlines inside the JSON string split one
// object across three physical lines, the helper rejected all three, and the
// reviewer got a malformed-line warning on the rail. The load-bearing assertion
// in this file is therefore the EXACT BYTES for text with newlines and quotes,
// plus the round trip back through protocol.parseReplyLine, which is the same
// parser the helper's fold uses.

"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const reply = require("../../src/cli/commands/reply.js");
const protocol = require("../../src/shared/protocol.js");

const REVIEW = "rev_test";

function aStateDir() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "lahe-reply-"));
  fs.mkdirSync(path.join(dir, "reviews", REVIEW), { recursive: true });
  return dir;
}

async function run(dir, args, options) {
  const stdout = [];
  const stderr = [];
  const code = await reply.run(
    ["--review", REVIEW, "--state-dir", dir].concat(args),
    Object.assign(
      {
        stdout: (text) => stdout.push(String(text)),
        stderr: (text) => stderr.push(String(text)),
        // No test reads the real stdin: an inherited pipe would make these
        // assertions depend on how the suite was launched.
        stdinIsTty: true
      },
      options || {}
    )
  );
  return { code: code, stdout: stdout.join(""), stderr: stderr.join("") };
}

function linesIn(dir, filename) {
  const file = path.join(dir, "reviews", REVIEW, filename);
  if (!fs.existsSync(file)) return null;
  return fs.readFileSync(file, "utf8").split("\n").filter((line) => line !== "");
}

// ---------------------------------------------------------------------------
// The bytes, which are the whole point
// ---------------------------------------------------------------------------

test("a text with paragraph breaks and quotes is ONE physical line the fold can read", async () => {
  const dir = aStateDir();
  const answer = 'Two things.\n\nFirst, the "wrapper" is gone.\nSecond, it is a tab \there.';
  const result = await run(dir, ["--item", "itm_ab12", "--rev", "2", "--status", "question", "--text", answer]);

  assert.equal(result.code, protocol.CLI_EXIT.OK, result.stderr);

  const raw = fs.readFileSync(path.join(dir, "reviews", REVIEW, "replies.jsonl"), "utf8");
  assert.equal(raw.split("\n").length, 2, "one line plus the trailing newline, never three");
  assert.equal(
    raw,
    '{"item":"itm_ab12","rev":2,"status":"question","text":"Two things.\\n\\nFirst, the \\"wrapper\\" is gone.\\nSecond, it is a tab \\there."}\n'
  );
  // The line it printed is the line it wrote, so an agent can see what landed.
  assert.equal(result.stdout, raw);

  const parsed = protocol.parseReplyLine(raw.trim(), { filenameAgent: null });
  assert.equal(parsed.ok, true, parsed.reason);
  assert.equal(parsed.reply[protocol.REPLY_FIELD.TEXT], answer, "the newlines survive the round trip");
});

test("every optional field lands under the protocol's own names, and appends rather than replaces", async () => {
  const dir = aStateDir();
  const first = await run(dir, [
    "--item", "itm_one", "--rev", "1", "--status", "not_handled",
    "--reason", "the source file is generated by a build I cannot run",
    "--agent", "claude", "--file", "src/a.html", "--file", "src/b.html", "--needs-see"
  ]);
  assert.equal(first.code, protocol.CLI_EXIT.OK, first.stderr);

  const second = await run(dir, ["--item", "itm_two", "--rev", "3", "--status", "handled", "--agent", "claude"]);
  assert.equal(second.code, protocol.CLI_EXIT.OK, second.stderr);

  const lines = linesIn(dir, "replies-claude.jsonl");
  assert.equal(lines.length, 2, "the second reply appended; nothing was rewritten");
  assert.deepEqual(JSON.parse(lines[0]), {
    item: "itm_one",
    rev: 1,
    status: "not_handled",
    agent: "claude",
    reason: "the source file is generated by a build I cannot run",
    files: ["src/a.html", "src/b.html"],
    user_needs_to_see_reply: true
  });
  // A handled reply carries nothing it was not given: no empty reason, no
  // false flag, nothing for the reviewer's card to render as blank.
  assert.deepEqual(JSON.parse(lines[1]), { item: "itm_two", rev: 3, status: "handled", agent: "claude" });
});

// ---------------------------------------------------------------------------
// Which file it writes
// ---------------------------------------------------------------------------

test("the file is replies.jsonl alone and replies-<agent>.jsonl with --agent", async () => {
  const dir = aStateDir();
  await run(dir, ["--item", "itm_a", "--rev", "1", "--status", "handled"]);
  assert.equal(linesIn(dir, "replies.jsonl").length, 1);
  assert.equal(linesIn(dir, "replies-claude.jsonl"), null);

  await run(dir, ["--item", "itm_a", "--rev", "1", "--status", "handled", "--agent", "claude"]);
  assert.equal(linesIn(dir, "replies-claude.jsonl").length, 1);
  assert.equal(linesIn(dir, "replies.jsonl").length, 1, "the shared file was not touched");

  // Both names are ones the helper's discovery will pick up.
  assert.equal(protocol.agentFromFilename("replies.jsonl").ok, true);
  assert.deepEqual(protocol.agentFromFilename("replies-claude.jsonl"), { ok: true, agent: "claude", reason: null });
});

test("an unknown review is refused before anything is written", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "lahe-reply-empty-"));
  const result = await run(dir, ["--item", "itm_a", "--rev", "1", "--status", "handled"]);
  assert.equal(result.code, protocol.CLI_EXIT.UNKNOWN_REVIEW);
  assert.match(result.stderr, /no review "rev_test"/);
  assert.equal(result.stdout, "");
});

// ---------------------------------------------------------------------------
// Refusals: one line, nothing written
// ---------------------------------------------------------------------------

test("the validation refusals name what is wrong and write no line at all", async () => {
  const cases = [
    { args: ["--item", "itm_a", "--rev", "1"], expect: /--status is required/ },
    { args: ["--item", "itm_a", "--rev", "1", "--status", "done"], expect: /--status must be one of handled, not_handled, question/ },
    { args: ["--rev", "1", "--status", "handled"], expect: /--item is required/ },
    { args: ["--item", "itm_a", "--status", "handled"], expect: /--rev is required/ },
    { args: ["--item", "itm_a", "--rev", "2.5", "--status", "handled"], expect: /--rev must be an integer/ },
    { args: ["--item", "itm_a", "--rev", "later", "--status", "handled"], expect: /--rev must be an integer/ },
    { args: ["--item", "itm_a", "--rev", "1", "--status", "question"], expect: /--status question needs --text/ },
    { args: ["--item", "itm_a", "--rev", "1", "--status", "not_handled"], expect: /--status not_handled needs --reason/ },
    { args: ["--item", "itm_a", "--rev", "1", "--status", "handled", "--needs-see"], expect: /--needs-see needs --text or --reason/ },
    { args: ["--item", "itm_a", "--rev", "1", "--status", "handled", "--agent", "../evil"], expect: /--agent names a file too/ },
    { args: ["--item", "../evil", "--rev", "1", "--status", "handled"], expect: /--item must be an item id/ },
    { args: ["--item", "itm_a", "--rev", "1", "--status", "handled", "--file"], expect: /--file needs a value/ },
    { args: ["--item", "itm_a", "--rev", "1", "--status", "handled", "--nope"], expect: /unknown option "--nope"/ }
  ];

  for (const one of cases) {
    const dir = aStateDir();
    const result = await run(dir, one.args);
    assert.equal(result.code, protocol.CLI_EXIT.BAD_USAGE, one.args.join(" "));
    assert.match(result.stderr, one.expect);
    assert.equal(result.stdout, "", one.args.join(" ") + " printed nothing on stdout");
    assert.equal(linesIn(dir, "replies.jsonl"), null, one.args.join(" ") + " wrote no file");
  }
});

test("the needs-see refusal quotes the contract rule rather than paraphrasing it", async () => {
  const reviewFormat = require("../../src/shared/review_format.js");
  const dir = aStateDir();
  const result = await run(dir, ["--item", "itm_a", "--rev", "1", "--status", "handled", "--needs-see"]);
  const quoted = "the flag counts only when the same line carries text or reason; flagging a reply with nothing in it sends the reviewer to a card that says nothing";
  assert.ok(result.stderr.includes(quoted), "the refusal carries the contract's own words");
  assert.ok(
    reviewFormat.CONTRACT.some((sentence) => sentence.includes(quoted)),
    "and those words are still in the contract"
  );
});

// ---------------------------------------------------------------------------
// stdin, so a long answer never goes through a shell quote
// ---------------------------------------------------------------------------

test("--text - reads stdin, keeping interior newlines and dropping one trailing newline", async () => {
  const dir = aStateDir();
  const result = await run(
    dir,
    ["--item", "itm_a", "--rev", "1", "--status", "question", "--text", "-"],
    { stdin: "first paragraph\n\nsecond paragraph\n" }
  );
  assert.equal(result.code, protocol.CLI_EXIT.OK, result.stderr);
  assert.deepEqual(JSON.parse(linesIn(dir, "replies.jsonl")[0]), {
    item: "itm_a",
    rev: 1,
    status: "question",
    text: "first paragraph\n\nsecond paragraph"
  });
});

test("a pipe with neither --text nor --reason is read as the text", async () => {
  const dir = aStateDir();
  const result = await run(
    dir,
    ["--item", "itm_a", "--rev", "1", "--status", "handled"],
    { stdin: "carried this into the template\n", stdinIsTty: false }
  );
  assert.equal(result.code, protocol.CLI_EXIT.OK, result.stderr);
  assert.equal(JSON.parse(linesIn(dir, "replies.jsonl")[0]).text, "carried this into the template");
});

test("a --reason given on the command line is not overwritten by an inherited pipe", async () => {
  const dir = aStateDir();
  await run(
    dir,
    ["--item", "itm_a", "--rev", "1", "--status", "not_handled", "--reason", "no such file"],
    { stdin: "something else entirely\n", stdinIsTty: false }
  );
  const written = JSON.parse(linesIn(dir, "replies.jsonl")[0]);
  assert.equal(written.reason, "no such file");
  assert.equal(Object.prototype.hasOwnProperty.call(written, "text"), false);
});

test("--text - with an empty stdin is a refusal, not a reply with nothing in it", async () => {
  const dir = aStateDir();
  const result = await run(dir, ["--item", "itm_a", "--rev", "1", "--status", "question", "--text", "-"], { stdin: "" });
  assert.equal(result.code, protocol.CLI_EXIT.BAD_USAGE);
  assert.match(result.stderr, /--text - read nothing from stdin/);
  assert.equal(linesIn(dir, "replies.jsonl"), null);
});

// ---------------------------------------------------------------------------
// The rev warning, which is a warning and never a refusal
// ---------------------------------------------------------------------------

test("a rev the projection disagrees with warns on stderr and still writes the line", async () => {
  const dir = aStateDir();
  const log = require("../../src/service/log.js").createEventLog({ dir: dir });
  const record = require("../../src/shared/record.js");
  const item = record.newItem({
    id: "itm_live",
    kind: record.KIND.COMMENT,
    state: record.STATE.READY,
    rev: 3,
    page_origin: record.FILE_ORIGIN,
    page_path: "brief.html",
    note: "tighten this"
  });
  log.append(REVIEW, [
    protocol.newEvent({
      event: protocol.EVENT.REVIEW_CREATED,
      event_id: "ev_created",
      review: REVIEW,
      payload: { token: "t".repeat(8) }
    }),
    protocol.newEvent({
      event: protocol.EVENT.ITEM_READY,
      event_id: "ev_item",
      review: REVIEW,
      item: item[record.FIELD.ID],
      rev: item[record.FIELD.REV],
      page_path: item[record.FIELD.PAGE_PATH],
      page_seq: item[record.FIELD.PAGE_SEQ],
      payload: { draft: false, record: item }
    })
  ]);

  const stale = await run(dir, ["--item", "itm_live", "--rev", "2", "--status", "handled"]);
  assert.equal(stale.code, protocol.CLI_EXIT.OK, "a second opinion about the rev never costs the agent its reply");
  assert.match(stale.stderr, /item itm_live is at rev 3 and you passed 2/);
  assert.equal(linesIn(dir, "replies.jsonl").length, 1);

  const current = await run(dir, ["--item", "itm_live", "--rev", "3", "--status", "handled"]);
  assert.equal(current.stderr, "", "the matching rev says nothing");

  const unknown = await run(dir, ["--item", "itm_nowhere", "--rev", "1", "--status", "handled"]);
  assert.equal(unknown.code, protocol.CLI_EXIT.OK);
  assert.match(unknown.stderr, /no item "itm_nowhere" in review rev_test/);
});

// ---------------------------------------------------------------------------
// Help
// ---------------------------------------------------------------------------

test("--help prints the usage on stdout and exits successfully", async () => {
  const dir = aStateDir();
  const result = await run(dir, ["--help"]);
  assert.equal(result.code, protocol.CLI_EXIT.OK);
  assert.match(result.stdout, /usage: lahe reply/);
  assert.equal(result.stderr, "");
});
